### PR TITLE
Adding --decrypt option to CLI. Fixing docs to not require a list of …

### PR DESCRIPTION
**Pull request by garnaat**
…tuples for encrypted_attributes since that can't be represented in JSON.

### CODE REVIEW

**Comment by garnaat** [comment]
Does this work for you @pas256 ?

**Comment by pas256** [comment]
Yup, sure does. Thanks!

**Comment by pas256** [comment]
Don't forget the version bump :)

**Comment by garnaat** [comment]
That will come in a minute 8^)

**Pull request merged**
